import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { Lock } from "lucide-react";
export function AchievementsDisplay({ achievements }) {
    const earned = achievements.filter(a => a.earned).length;
    const total = achievements.length;
    return (_jsxs(Card, { children: [_jsxs(CardHeader, { children: [_jsxs(CardTitle, { className: "flex items-center justify-between", children: [_jsx("span", { children: "Achievements" }), _jsxs(Badge, { variant: "secondary", children: [earned, "/", total] })] }), _jsx(CardDescription, { children: "Track your progress and unlock achievements" })] }), _jsx(CardContent, { children: _jsx("div", { className: "grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4", children: achievements.map((achievement) => (_jsx(TooltipProvider, { children: _jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsxs("div", { className: `relative p-4 border rounded-lg text-center transition-all ${achievement.earned
                                            ? 'bg-primary/5 border-primary/20 hover:border-primary/40'
                                            : 'bg-muted/30 border-muted hover:border-muted-foreground/20 opacity-60'}`, children: [!achievement.earned && (_jsx("div", { className: "absolute top-2 right-2", children: _jsx(Lock, { className: "h-3 w-3 text-muted-foreground" }) })), _jsx("div", { className: "text-4xl mb-2", children: achievement.icon }), _jsx("div", { className: "text-sm font-semibold mb-1 line-clamp-1", children: achievement.title }), !achievement.earned && achievement.progress !== undefined && achievement.target && (_jsx(Progress, { value: (achievement.progress / achievement.target) * 100, className: "h-1 mt-2" }))] }) }), _jsxs(TooltipContent, { side: "top", className: "max-w-xs", children: [_jsx("p", { className: "font-semibold", children: achievement.title }), _jsx("p", { className: "text-xs text-muted-foreground", children: achievement.description }), !achievement.earned && achievement.progress !== undefined && achievement.target && (_jsxs("p", { className: "text-xs mt-1", children: ["Progress: ", achievement.progress, "/", achievement.target] })), achievement.earned && (_jsx(Badge, { variant: "secondary", className: "mt-1", children: "\u2713 Unlocked" }))] })] }) }, achievement.id))) }) })] }));
}
