import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Skeleton } from "@/components/ui/skeleton";
import { Card } from "@/components/ui/card";
export function GeneratorSkeleton() {
    return (_jsxs("div", { className: "min-h-screen bg-gradient-subtle", children: [_jsx("header", { className: "sticky top-0 z-50 border-b border-border bg-background/95 backdrop-blur", children: _jsx("div", { className: "container mx-auto px-4 py-4", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsx(Skeleton, { className: "h-8 w-32" }), _jsx(Skeleton, { className: "h-10 w-40" })] }) }) }), _jsx("main", { className: "container mx-auto px-4 py-12", children: _jsxs("div", { className: "mx-auto max-w-4xl", children: [_jsxs("div", { className: "mb-8 text-center space-y-2", children: [_jsx(Skeleton, { className: "h-10 w-96 mx-auto" }), _jsx(Skeleton, { className: "h-5 w-64 mx-auto" })] }), _jsx(Card, { className: "p-8", children: _jsxs("div", { className: "space-y-6", children: [_jsx(Skeleton, { className: "h-20 w-full" }), [1, 2, 3, 4, 5].map((i) => (_jsxs("div", { className: "space-y-2", children: [_jsx(Skeleton, { className: "h-4 w-32" }), _jsx(Skeleton, { className: "h-10 w-full" })] }, i))), _jsxs("div", { className: "flex gap-4", children: [_jsx(Skeleton, { className: "h-10 flex-1" }), _jsx(Skeleton, { className: "h-10 flex-1" })] })] }) })] }) })] }));
}
export function DashboardSkeleton() {
    return (_jsxs("div", { className: "min-h-screen bg-gradient-subtle", children: [_jsx("header", { className: "border-b border-border bg-background/95 backdrop-blur", children: _jsx("div", { className: "container mx-auto px-4 py-4", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsx(Skeleton, { className: "h-8 w-48" }), _jsx(Skeleton, { className: "h-10 w-24" })] }) }) }), _jsxs("main", { className: "container mx-auto px-4 py-8", children: [_jsx(Card, { className: "p-6 mb-8", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "space-y-2", children: [_jsx(Skeleton, { className: "h-8 w-64" }), _jsx(Skeleton, { className: "h-4 w-48" })] }), _jsx(Skeleton, { className: "h-10 w-40" })] }) }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-6 mb-8", children: [1, 2, 3].map((i) => (_jsx(Card, { className: "p-6", children: _jsxs("div", { className: "flex items-center gap-4", children: [_jsx(Skeleton, { className: "h-12 w-12 rounded-full" }), _jsxs("div", { className: "space-y-2", children: [_jsx(Skeleton, { className: "h-4 w-24" }), _jsx(Skeleton, { className: "h-6 w-16" })] })] }) }, i))) }), _jsx(Card, { className: "p-6", children: _jsx("div", { className: "space-y-4", children: [1, 2, 3].map((i) => (_jsx(Skeleton, { className: "h-24 w-full" }, i))) }) })] })] }));
}
export function TableSkeleton() {
    return (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx(Skeleton, { className: "h-10 w-[250px]" }), _jsx(Skeleton, { className: "h-10 w-[100px]" })] }), _jsxs("div", { className: "border rounded-md", children: [_jsx("div", { className: "p-4 border-b bg-muted/50", children: _jsxs("div", { className: "flex gap-4", children: [_jsx(Skeleton, { className: "h-4 w-1/4" }), _jsx(Skeleton, { className: "h-4 w-1/4" }), _jsx(Skeleton, { className: "h-4 w-1/4" }), _jsx(Skeleton, { className: "h-4 w-1/4" })] }) }), [1, 2, 3, 4, 5].map((i) => (_jsx("div", { className: "p-4 border-b last:border-0", children: _jsxs("div", { className: "flex gap-4", children: [_jsx(Skeleton, { className: "h-4 w-1/4" }), _jsx(Skeleton, { className: "h-4 w-1/4" }), _jsx(Skeleton, { className: "h-4 w-1/4" }), _jsx(Skeleton, { className: "h-4 w-1/4" })] }) }, i)))] })] }));
}
export function ProfileSkeleton() {
    return (_jsxs("div", { className: "min-h-screen bg-gradient-subtle", children: [_jsx(Skeleton, { className: "h-16 w-full" }), _jsx("div", { className: "container mx-auto px-4 py-8", children: _jsxs(Card, { className: "max-w-2xl mx-auto p-6 space-y-8", children: [_jsxs("div", { className: "flex items-center gap-4 border-b pb-6", children: [_jsx(Skeleton, { className: "h-24 w-24 rounded-full" }), _jsxs("div", { className: "space-y-2", children: [_jsx(Skeleton, { className: "h-8 w-48" }), _jsx(Skeleton, { className: "h-4 w-32" })] })] }), _jsx("div", { className: "space-y-4", children: [1, 2, 3, 4].map((i) => (_jsxs("div", { className: "space-y-2", children: [_jsx(Skeleton, { className: "h-4 w-24" }), _jsx(Skeleton, { className: "h-10 w-full" })] }, i))) }), _jsx(Skeleton, { className: "h-10 w-full" })] }) })] }));
}
