// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uihhwjloceffyksuscmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpaGh3amxvY2VmZnlrc3VzY21nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4MTcxNzEsImV4cCI6MjA3ODM5MzE3MX0.8TUjSwZh_VdgyDSS9poWds23Ge9j2SArPs9peh9LESs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});